//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18051
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 11.0.50727.1
// 
namespace AgenceRT.AgenceWebService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BienDTO", Namespace="http://schemas.datacontract.org/2004/07/AgenceDTO")]
    public partial class BienDTO : AgenceRT.AgenceWebService.TypeBienDTO {
        
        private string AdresseField;
        
        private string DescriptionField;
        
        private int IdBienField;
        
        private string LatitudeField;
        
        private string LongitudeField;
        
        private AgenceRT.AgenceWebService.ProprietaireDTO ProprietaireField;
        
        private string TitreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresse {
            get {
                return this.AdresseField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresseField, value) != true)) {
                    this.AdresseField = value;
                    this.RaisePropertyChanged("Adresse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdBien {
            get {
                return this.IdBienField;
            }
            set {
                if ((this.IdBienField.Equals(value) != true)) {
                    this.IdBienField = value;
                    this.RaisePropertyChanged("IdBien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudeField, value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeField, value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AgenceRT.AgenceWebService.ProprietaireDTO Proprietaire {
            get {
                return this.ProprietaireField;
            }
            set {
                if ((object.ReferenceEquals(this.ProprietaireField, value) != true)) {
                    this.ProprietaireField = value;
                    this.RaisePropertyChanged("Proprietaire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titre {
            get {
                return this.TitreField;
            }
            set {
                if ((object.ReferenceEquals(this.TitreField, value) != true)) {
                    this.TitreField = value;
                    this.RaisePropertyChanged("Titre");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeBienDTO", Namespace="http://schemas.datacontract.org/2004/07/AgenceDTO")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AgenceRT.AgenceWebService.BienDTO))]
    public partial class TypeBienDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdTypeBienField;
        
        private string LibelleTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTypeBien {
            get {
                return this.IdTypeBienField;
            }
            set {
                if ((this.IdTypeBienField.Equals(value) != true)) {
                    this.IdTypeBienField = value;
                    this.RaisePropertyChanged("IdTypeBien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LibelleType {
            get {
                return this.LibelleTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.LibelleTypeField, value) != true)) {
                    this.LibelleTypeField = value;
                    this.RaisePropertyChanged("LibelleType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProprietaireDTO", Namespace="http://schemas.datacontract.org/2004/07/AgenceDTO")]
    public partial class ProprietaireDTO : AgenceRT.AgenceWebService.PersonneDTO {
        
        private string AdresseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresse {
            get {
                return this.AdresseField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresseField, value) != true)) {
                    this.AdresseField = value;
                    this.RaisePropertyChanged("Adresse");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonneDTO", Namespace="http://schemas.datacontract.org/2004/07/AgenceDTO")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AgenceRT.AgenceWebService.ProspectDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AgenceRT.AgenceWebService.AgentDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AgenceRT.AgenceWebService.ProprietaireDTO))]
    public partial class PersonneDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdPersonneField;
        
        private string NomField;
        
        private string PrenomField;
        
        private string TelephoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPersonne {
            get {
                return this.IdPersonneField;
            }
            set {
                if ((this.IdPersonneField.Equals(value) != true)) {
                    this.IdPersonneField = value;
                    this.RaisePropertyChanged("IdPersonne");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenom {
            get {
                return this.PrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenomField, value) != true)) {
                    this.PrenomField = value;
                    this.RaisePropertyChanged("Prenom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProspectDTO", Namespace="http://schemas.datacontract.org/2004/07/AgenceDTO")]
    public partial class ProspectDTO : AgenceRT.AgenceWebService.PersonneDTO {
        
        private System.Nullable<System.DateTime> DateContactField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateContact {
            get {
                return this.DateContactField;
            }
            set {
                if ((this.DateContactField.Equals(value) != true)) {
                    this.DateContactField = value;
                    this.RaisePropertyChanged("DateContact");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentDTO", Namespace="http://schemas.datacontract.org/2004/07/AgenceDTO")]
    public partial class AgentDTO : AgenceRT.AgenceWebService.PersonneDTO {
        
        private string LoginField;
        
        private string MotDePasseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotDePasse {
            get {
                return this.MotDePasseField;
            }
            set {
                if ((object.ReferenceEquals(this.MotDePasseField, value) != true)) {
                    this.MotDePasseField = value;
                    this.RaisePropertyChanged("MotDePasse");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgendaDTO", Namespace="http://schemas.datacontract.org/2004/07/AgenceDTO")]
    public partial class AgendaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AgenceRT.AgenceWebService.AgentDTO AgentField;
        
        private AgenceRT.AgenceWebService.AnnonceDTO AnnonceField;
        
        private System.Nullable<System.DateTime> DateField;
        
        private string DescriptionField;
        
        private int IdAgendaField;
        
        private AgenceRT.AgenceWebService.ProspectDTO ProspectField;
        
        private string TitreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AgenceRT.AgenceWebService.AgentDTO Agent {
            get {
                return this.AgentField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentField, value) != true)) {
                    this.AgentField = value;
                    this.RaisePropertyChanged("Agent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AgenceRT.AgenceWebService.AnnonceDTO Annonce {
            get {
                return this.AnnonceField;
            }
            set {
                if ((object.ReferenceEquals(this.AnnonceField, value) != true)) {
                    this.AnnonceField = value;
                    this.RaisePropertyChanged("Annonce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAgenda {
            get {
                return this.IdAgendaField;
            }
            set {
                if ((this.IdAgendaField.Equals(value) != true)) {
                    this.IdAgendaField = value;
                    this.RaisePropertyChanged("IdAgenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AgenceRT.AgenceWebService.ProspectDTO Prospect {
            get {
                return this.ProspectField;
            }
            set {
                if ((object.ReferenceEquals(this.ProspectField, value) != true)) {
                    this.ProspectField = value;
                    this.RaisePropertyChanged("Prospect");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titre {
            get {
                return this.TitreField;
            }
            set {
                if ((object.ReferenceEquals(this.TitreField, value) != true)) {
                    this.TitreField = value;
                    this.RaisePropertyChanged("Titre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnnonceDTO", Namespace="http://schemas.datacontract.org/2004/07/AgenceDTO")]
    public partial class AnnonceDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AgenceRT.AgenceWebService.BienDTO BienField;
        
        private int IdAnnonceField;
        
        private float PrixField;
        
        private string TexteField;
        
        private string TitreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AgenceRT.AgenceWebService.BienDTO Bien {
            get {
                return this.BienField;
            }
            set {
                if ((object.ReferenceEquals(this.BienField, value) != true)) {
                    this.BienField = value;
                    this.RaisePropertyChanged("Bien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAnnonce {
            get {
                return this.IdAnnonceField;
            }
            set {
                if ((this.IdAnnonceField.Equals(value) != true)) {
                    this.IdAnnonceField = value;
                    this.RaisePropertyChanged("IdAnnonce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Prix {
            get {
                return this.PrixField;
            }
            set {
                if ((this.PrixField.Equals(value) != true)) {
                    this.PrixField = value;
                    this.RaisePropertyChanged("Prix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texte {
            get {
                return this.TexteField;
            }
            set {
                if ((object.ReferenceEquals(this.TexteField, value) != true)) {
                    this.TexteField = value;
                    this.RaisePropertyChanged("Texte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titre {
            get {
                return this.TitreField;
            }
            set {
                if ((object.ReferenceEquals(this.TitreField, value) != true)) {
                    this.TitreField = value;
                    this.RaisePropertyChanged("Titre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AgenceWebService.IAgenceWebServices")]
    public interface IAgenceWebServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenceWebServices/ChargerListeBiens", ReplyAction="http://tempuri.org/IAgenceWebServices/ChargerListeBiensResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<AgenceRT.AgenceWebService.BienDTO>> ChargerListeBiensAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenceWebServices/ChargerBien", ReplyAction="http://tempuri.org/IAgenceWebServices/ChargerBienResponse")]
        System.Threading.Tasks.Task<AgenceRT.AgenceWebService.BienDTO> ChargerBienAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenceWebServices/ChargerListeBiensParType", ReplyAction="http://tempuri.org/IAgenceWebServices/ChargerListeBiensParTypeResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<AgenceRT.AgenceWebService.BienDTO>> ChargerListeBiensParTypeAsync(string idType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenceWebServices/AjouterBien", ReplyAction="http://tempuri.org/IAgenceWebServices/AjouterBienResponse")]
        System.Threading.Tasks.Task AjouterBienAsync(AgenceRT.AgenceWebService.BienDTO bien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenceWebServices/ChargerListeTypesBiens", ReplyAction="http://tempuri.org/IAgenceWebServices/ChargerListeTypesBiensResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<AgenceRT.AgenceWebService.TypeBienDTO>> ChargerListeTypesBiensAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenceWebServices/SupprimerBien", ReplyAction="http://tempuri.org/IAgenceWebServices/SupprimerBienResponse")]
        System.Threading.Tasks.Task SupprimerBienAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenceWebServices/ChargerListeProspects", ReplyAction="http://tempuri.org/IAgenceWebServices/ChargerListeProspectsResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<AgenceRT.AgenceWebService.ProspectDTO>> ChargerListeProspectsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenceWebServices/ChargerProspect", ReplyAction="http://tempuri.org/IAgenceWebServices/ChargerProspectResponse")]
        System.Threading.Tasks.Task<AgenceRT.AgenceWebService.ProspectDTO> ChargerProspectAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenceWebServices/AjouterProspect", ReplyAction="http://tempuri.org/IAgenceWebServices/AjouterProspectResponse")]
        System.Threading.Tasks.Task AjouterProspectAsync(AgenceRT.AgenceWebService.ProspectDTO prospect);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenceWebServices/SupprimerProspect", ReplyAction="http://tempuri.org/IAgenceWebServices/SupprimerProspectResponse")]
        System.Threading.Tasks.Task SupprimerProspectAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenceWebServices/ChargerListeAgents", ReplyAction="http://tempuri.org/IAgenceWebServices/ChargerListeAgentsResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<AgenceRT.AgenceWebService.AgentDTO>> ChargerListeAgentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenceWebServices/ChargerAgent", ReplyAction="http://tempuri.org/IAgenceWebServices/ChargerAgentResponse")]
        System.Threading.Tasks.Task<AgenceRT.AgenceWebService.AgentDTO> ChargerAgentAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenceWebServices/AjouterAgent", ReplyAction="http://tempuri.org/IAgenceWebServices/AjouterAgentResponse")]
        System.Threading.Tasks.Task AjouterAgentAsync(AgenceRT.AgenceWebService.AgentDTO agent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenceWebServices/SupprimerAgent", ReplyAction="http://tempuri.org/IAgenceWebServices/SupprimerAgentResponse")]
        System.Threading.Tasks.Task SupprimerAgentAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenceWebServices/ChargerListeProprietaires", ReplyAction="http://tempuri.org/IAgenceWebServices/ChargerListeProprietairesResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<AgenceRT.AgenceWebService.ProprietaireDTO>> ChargerListeProprietairesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenceWebServices/ChargerProprietaire", ReplyAction="http://tempuri.org/IAgenceWebServices/ChargerProprietaireResponse")]
        System.Threading.Tasks.Task<AgenceRT.AgenceWebService.ProprietaireDTO> ChargerProprietaireAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenceWebServices/AjouterProprietaire", ReplyAction="http://tempuri.org/IAgenceWebServices/AjouterProprietaireResponse")]
        System.Threading.Tasks.Task AjouterProprietaireAsync(AgenceRT.AgenceWebService.ProprietaireDTO proprietaire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenceWebServices/SupprimerProprietaire", ReplyAction="http://tempuri.org/IAgenceWebServices/SupprimerProprietaireResponse")]
        System.Threading.Tasks.Task SupprimerProprietaireAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenceWebServices/ChargerListeRendezVous", ReplyAction="http://tempuri.org/IAgenceWebServices/ChargerListeRendezVousResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<AgenceRT.AgenceWebService.AgendaDTO>> ChargerListeRendezVousAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenceWebServices/ChargerAgenda", ReplyAction="http://tempuri.org/IAgenceWebServices/ChargerAgendaResponse")]
        System.Threading.Tasks.Task<AgenceRT.AgenceWebService.AgendaDTO> ChargerAgendaAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenceWebServices/AjouterAgenda", ReplyAction="http://tempuri.org/IAgenceWebServices/AjouterAgendaResponse")]
        System.Threading.Tasks.Task AjouterAgendaAsync(AgenceRT.AgenceWebService.AgendaDTO agenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenceWebServices/SupprimerAgenda", ReplyAction="http://tempuri.org/IAgenceWebServices/SupprimerAgendaResponse")]
        System.Threading.Tasks.Task SupprimerAgendaAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenceWebServices/ChargerListeAnnonces", ReplyAction="http://tempuri.org/IAgenceWebServices/ChargerListeAnnoncesResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<AgenceRT.AgenceWebService.AnnonceDTO>> ChargerListeAnnoncesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenceWebServices/ChargerAnnonce", ReplyAction="http://tempuri.org/IAgenceWebServices/ChargerAnnonceResponse")]
        System.Threading.Tasks.Task<AgenceRT.AgenceWebService.AnnonceDTO> ChargerAnnonceAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenceWebServices/AjouterAnnonce", ReplyAction="http://tempuri.org/IAgenceWebServices/AjouterAnnonceResponse")]
        System.Threading.Tasks.Task AjouterAnnonceAsync(AgenceRT.AgenceWebService.AnnonceDTO annonce);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenceWebServices/SupprimerAnnonce", ReplyAction="http://tempuri.org/IAgenceWebServices/SupprimerAnnonceResponse")]
        System.Threading.Tasks.Task SupprimerAnnonceAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenceWebServices/EnregistrerSaisie", ReplyAction="http://tempuri.org/IAgenceWebServices/EnregistrerSaisieResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<AgenceRT.AgenceWebService.BienDTO>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgenceRT.AgenceWebService.BienDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgenceRT.AgenceWebService.TypeBienDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgenceRT.AgenceWebService.ProprietaireDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgenceRT.AgenceWebService.PersonneDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<AgenceRT.AgenceWebService.TypeBienDTO>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<AgenceRT.AgenceWebService.ProspectDTO>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgenceRT.AgenceWebService.ProspectDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<AgenceRT.AgenceWebService.AgentDTO>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgenceRT.AgenceWebService.AgentDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<AgenceRT.AgenceWebService.ProprietaireDTO>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<AgenceRT.AgenceWebService.AgendaDTO>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgenceRT.AgenceWebService.AgendaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgenceRT.AgenceWebService.AnnonceDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<AgenceRT.AgenceWebService.AnnonceDTO>))]
        System.Threading.Tasks.Task EnregistrerSaisieAsync(object saisie);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAgenceWebServicesChannel : AgenceRT.AgenceWebService.IAgenceWebServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgenceWebServicesClient : System.ServiceModel.ClientBase<AgenceRT.AgenceWebService.IAgenceWebServices>, AgenceRT.AgenceWebService.IAgenceWebServices {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AgenceWebServicesClient() : 
                base(AgenceWebServicesClient.GetDefaultBinding(), AgenceWebServicesClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IAgenceWebServices.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AgenceWebServicesClient(EndpointConfiguration endpointConfiguration) : 
                base(AgenceWebServicesClient.GetBindingForEndpoint(endpointConfiguration), AgenceWebServicesClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AgenceWebServicesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AgenceWebServicesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AgenceWebServicesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AgenceWebServicesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AgenceWebServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<AgenceRT.AgenceWebService.BienDTO>> ChargerListeBiensAsync() {
            return base.Channel.ChargerListeBiensAsync();
        }
        
        public System.Threading.Tasks.Task<AgenceRT.AgenceWebService.BienDTO> ChargerBienAsync(string id) {
            return base.Channel.ChargerBienAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<AgenceRT.AgenceWebService.BienDTO>> ChargerListeBiensParTypeAsync(string idType) {
            return base.Channel.ChargerListeBiensParTypeAsync(idType);
        }
        
        public System.Threading.Tasks.Task AjouterBienAsync(AgenceRT.AgenceWebService.BienDTO bien) {
            return base.Channel.AjouterBienAsync(bien);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<AgenceRT.AgenceWebService.TypeBienDTO>> ChargerListeTypesBiensAsync() {
            return base.Channel.ChargerListeTypesBiensAsync();
        }
        
        public System.Threading.Tasks.Task SupprimerBienAsync(string id) {
            return base.Channel.SupprimerBienAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<AgenceRT.AgenceWebService.ProspectDTO>> ChargerListeProspectsAsync() {
            return base.Channel.ChargerListeProspectsAsync();
        }
        
        public System.Threading.Tasks.Task<AgenceRT.AgenceWebService.ProspectDTO> ChargerProspectAsync(string id) {
            return base.Channel.ChargerProspectAsync(id);
        }
        
        public System.Threading.Tasks.Task AjouterProspectAsync(AgenceRT.AgenceWebService.ProspectDTO prospect) {
            return base.Channel.AjouterProspectAsync(prospect);
        }
        
        public System.Threading.Tasks.Task SupprimerProspectAsync(string id) {
            return base.Channel.SupprimerProspectAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<AgenceRT.AgenceWebService.AgentDTO>> ChargerListeAgentsAsync() {
            return base.Channel.ChargerListeAgentsAsync();
        }
        
        public System.Threading.Tasks.Task<AgenceRT.AgenceWebService.AgentDTO> ChargerAgentAsync(string id) {
            return base.Channel.ChargerAgentAsync(id);
        }
        
        public System.Threading.Tasks.Task AjouterAgentAsync(AgenceRT.AgenceWebService.AgentDTO agent) {
            return base.Channel.AjouterAgentAsync(agent);
        }
        
        public System.Threading.Tasks.Task SupprimerAgentAsync(string id) {
            return base.Channel.SupprimerAgentAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<AgenceRT.AgenceWebService.ProprietaireDTO>> ChargerListeProprietairesAsync() {
            return base.Channel.ChargerListeProprietairesAsync();
        }
        
        public System.Threading.Tasks.Task<AgenceRT.AgenceWebService.ProprietaireDTO> ChargerProprietaireAsync(string id) {
            return base.Channel.ChargerProprietaireAsync(id);
        }
        
        public System.Threading.Tasks.Task AjouterProprietaireAsync(AgenceRT.AgenceWebService.ProprietaireDTO proprietaire) {
            return base.Channel.AjouterProprietaireAsync(proprietaire);
        }
        
        public System.Threading.Tasks.Task SupprimerProprietaireAsync(string id) {
            return base.Channel.SupprimerProprietaireAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<AgenceRT.AgenceWebService.AgendaDTO>> ChargerListeRendezVousAsync() {
            return base.Channel.ChargerListeRendezVousAsync();
        }
        
        public System.Threading.Tasks.Task<AgenceRT.AgenceWebService.AgendaDTO> ChargerAgendaAsync(string id) {
            return base.Channel.ChargerAgendaAsync(id);
        }
        
        public System.Threading.Tasks.Task AjouterAgendaAsync(AgenceRT.AgenceWebService.AgendaDTO agenda) {
            return base.Channel.AjouterAgendaAsync(agenda);
        }
        
        public System.Threading.Tasks.Task SupprimerAgendaAsync(string id) {
            return base.Channel.SupprimerAgendaAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<AgenceRT.AgenceWebService.AnnonceDTO>> ChargerListeAnnoncesAsync() {
            return base.Channel.ChargerListeAnnoncesAsync();
        }
        
        public System.Threading.Tasks.Task<AgenceRT.AgenceWebService.AnnonceDTO> ChargerAnnonceAsync(string id) {
            return base.Channel.ChargerAnnonceAsync(id);
        }
        
        public System.Threading.Tasks.Task AjouterAnnonceAsync(AgenceRT.AgenceWebService.AnnonceDTO annonce) {
            return base.Channel.AjouterAnnonceAsync(annonce);
        }
        
        public System.Threading.Tasks.Task SupprimerAnnonceAsync(string id) {
            return base.Channel.SupprimerAnnonceAsync(id);
        }
        
        public System.Threading.Tasks.Task EnregistrerSaisieAsync(object saisie) {
            return base.Channel.EnregistrerSaisieAsync(saisie);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAgenceWebServices)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAgenceWebServices)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:55775/AgenceWebServices.svc/soap");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return AgenceWebServicesClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IAgenceWebServices);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return AgenceWebServicesClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IAgenceWebServices);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IAgenceWebServices,
        }
    }
}
